### ISSUE TITLE
Delete button not working for child terms

### ISSUE THREAD

**Issue by Trexology** [DevFactoryCH/taxonomy#10]
Hi is me again!

at terms index.blade

line: 134 should be
{!! Form::open(array('method' => 'DELETE', 'url' => action('\Devfactory\Taxonomy\Controllers\TermsController@deleteDestroy', $child->id))) !!}

currently child terms delete button is pointing to getEdit method which will fail. Thanks.

**Comment by sirsquall** [comment]
Thanks it's fixed
