### ISSUE TITLE
Support for PHP 7

### ISSUE THREAD

**Issue by kohenkatz** [DevFactoryCH/taxonomy#11]
As far as I can tell, this package works in the PHP 7 Release Candidates.

However, the `composer.json` specifies the PHP requirement as `~5.4`, meaning that it cannot be installed on a machine running PHP 7.

The `composer.json` should probably be updated to allow newer versions.

**Comment by markcameron** [comment]
Hi, sorry about forgetting about this guy, I've updated the package to allow for PHP 7. Version `3.0.7` now supports it.
