### ISSUE TITLE
getAllByTermId cater to multiple terms?

### ISSUE THREAD

**Issue by Trexology** [DevFactoryCH/taxonomy#12]
taxonomytrait only allow getting all entities in one term id

Is it possible to search for entities which contains multiple term id?? For both AND and OR operations?
(e.g cars with term id: 1 AND 23)
(e.g cars with term id: 13 OR 82)

**Comment by markcameron** [comment]
I've changed the call to `getAllByTermId()` to allow arrays of ID's as well.

It does an OR, I'm not sure I can do an AND on the polymorphic relation, at least I didn't manage to in my limited testing...
