### ISSUE TITLE
Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared() 

### ISSUE THREAD

**Issue by brmn** [DevFactoryCH/taxonomy#14]
Laravel 5.2

after installing "devfactory/taxonomy": "3.0.*" and adding 
'Devfactory\Taxonomy\TaxonomyServiceProvider', to providers in app.php

got

  [Symfony\Component\Debug\Exception\FatalThrowableError]                                
  Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()

because of vendor/devfactory/taxonomy/src/TaxonomyServiceProvider.php:53
$this->app->bindShared('taxonomy', function ($app) {...

change bindShared() to singleton() to fix

**Comment by markcameron** [comment]
Sorry for the delay, released a new version `3.0.10` with the fix.

Thanks for the headsup.
