### ISSUE TITLE
Trait 'Illuminate\Foundation\Bus\DispatchesCommands' not found

### ISSUE THREAD

**Issue by Trexology** [DevFactoryCH/taxonomy#15]
Fatal error for laravel 5.2

need to change to use Illuminate\Foundation\Bus\DispatchesJobs;

refer to:

http://stackoverflow.com/questions/34589987/trait-illuminate-foundation-bus-dispatchescommands-not-found-error-while-larav

**Comment by markcameron** [comment]
Fixed a while back if you use the `3.1.*` version. Apologies for the delay.
