### ISSUE TITLE
CRUD routes?

### ISSUE THREAD

**Issue by richardsweeney** [DevFactoryCH/taxonomy#23]
Hej! I'm a Laravel n00b so apologies if this is a stupid question.

It seems there are some Routes defined in the package, but they're not listen when I run `php artisan route:list`. Are they intended for public consumption and if so, how does one go about using them?!

Thanks!

**Comment by markcameron** [comment]
Hi,

Yeah they were more internal than anything else. There's a basic administration of the different vocabularies and terms that is fed by those routes and the included views in the package as well. I forget off the top of my head, but I think you can publish the views, and then if you add to your `routes.php`/`web.php` file:

```
Route::resource('taxonomy', 'Devfactory\Taxonomy\Controllers\TaxonomyController');
Route::resource('taxonomy', 'Devfactory\Taxonomy\Controllers\TermsController');
```

Then in the config file you can configure the variables for the layouts:

```
  'layout' => [
    'extends' => 'layouts.admin',
    'header' => 'header',
    'content' => 'content',
  ],
```

Where `extends` is you layout, and then `header` is the name of you `@yield('')` section for the header and `content` the one for you content yield.

Give it a try, and let me know if you run in to any issues. Can't guarantee it all works perfectly, haven't used it in a while.

**Comment by richardsweeney** [comment]
Thanks @markcameron !
