### ISSUE TITLE
Eager loading for relationships

### ISSUE THREAD

**Issue by richardsweeney** [DevFactoryCH/taxonomy#24]
Hey!

Is it possible to use eager loading for terms related to model?

[https://laravel.com/docs/5.3/eloquent-relationships#eager-loading](https://laravel.com/docs/5.3/eloquent-relationships#eager-loading)

**Comment by markcameron** [comment]
Hey,

You got an example of the code you're using? Trying to see with which call to the package you're needing it, then I can see what can be done.

Thanks

**Comment by richardsweeney** [comment]
@markcameron I'm thinking something like the code below, but I don't know how this would be implemented in this case... 

    <?php
    
    $rules = Rule::paginate(20);
    $rules->load('term');

**Comment by markcameron** [comment]
Hmm yeah, it's not ideal the way I built this package all those years ago!

What you can do is:

```
$rules = Rule::with('related')->paginate(20);

foreach ($rules as $rule) {
  echo $rule->related->name;
}
```

And then you can access the terms for that `$rule`, only issue is if you have more than one vocabulary for that term, you'll get all the terms from all associated vocabularies mixed in, so you'd need to do some post filtering with a `whereHas()` query or something to only get a specific vocabulary.

**Comment by richardsweeney** [comment]
Thanks @markcameron ! It works :)
