### ISSUE TITLE
Documentation: Update old README files to point to here

### ISSUE THREAD

**Issue by kohenkatz** [DevFactoryCH/taxonomy#3]
https://github.com/xdubois/taxonomy-laravel-bundle and https://bitbucket.org/devfactory/taxonomy-laravel-bundle/overview both appear to be older versions of this package.  The README files there really should be updated to point to this new version.

**Comment by markcameron** [comment]
Thanks, made the requisite changes. The old GitHub one used to have a README informing users, but I must have overwritten it with a push to the wrong remote!
