### ISSUE TITLE
Warning when performing composer install or composer update

### ISSUE THREAD

**Issue by Trexology** [DevFactoryCH/taxonomy#9]
Below are the warning displayed:

Warning: Ambiguous class resolution, "CreateVocabulariesTable" was found in both "$baseDir . '/database/migrations/2014_10_29_164909_create_vocabularies_table.php" and "/Users/admin/Development/laravel5-default/vendor/devfactory/taxonomy/src/migrations/2014_10_29_164909_create_vocabularies_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateTermsTable" was found in both "$baseDir . '/database/migrations/2014_10_29_164925_create_terms_table.php" and "/Users/admin/Development/laravel5-default/vendor/devfactory/taxonomy/src/migrations/2014_10_29_164925_create_terms_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateTermRelationsTable" was found in both "$baseDir . '/database/migrations/2014_10_29_164940_create_term_relations_table.php" and "/Users/admin/Development/laravel5-default/vendor/devfactory/taxonomy/src/migrations/2014_10_29_164940_create_term_relations_table.php", the first will be used.

Could be due to autoload issues. 
Performance/Functionalities of the codes are not affected by this.
Using laravel 5.1 and 3.0 Branch.

**Comment by sirsquall** [comment]
Hi,

It's fixed in the new release 3.0.2
